spring.application.name=${SPRING_APPLICATION_NAME}
server.port=${SERVER_PORT}

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always
spring.jpa.open-in-view=false

prism.ollama.base-url=${PRISM_OLLAMA_BASE_URL}
prism.ollama.chat-model=${PRISM_OLLAMA_CHAT_MODEL}
prism.ollama.intent-model=${PRISM_OLLAMA_INTENT_MODEL}
prism.ollama.keep-alive=${PRISM_OLLAMA_KEEP_ALIVE}
prism.ollama.chat-temperature=${PRISM_OLLAMA_CHAT_TEMPERATURE}
prism.ollama.intent-temperature=${PRISM_OLLAMA_INTENT_TEMPERATURE}
prism.embedding.tokenizer-resource=${PRISM_EMBEDDING_TOKENIZER_RESOURCE}
prism.embedding.model-resource=${PRISM_EMBEDDING_MODEL_RESOURCE}

prism.embedding.quantized-tokenizer-resource=${PRISM_EMBEDDING_QUANTIZED_TOKENIZER_RESOURCE}
prism.embedding.quantized-model-resource=${PRISM_EMBEDDING_QUANTIZED_MODEL_RESOURCE}

spring.data.redis.host=${SPRING_DATA_REDIS_HOST}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT}

DOC_STORAGE_ROOT_PATH=${PRISM_DOC_STORAGE_PATH}
